### ISSUE TITLE
Error: illegal start of expression

### ISSUE THREAD

**Issue by bhelmick** [dengyull/Synology-vsmeta#1]
First, THANK YOU FOR DOING THIS! For those of us with Synology NAS devices, we've long suffered with their incredibly poor metadata system. This tool will be super useful for converting an existing NFO from 3rd party library management apps into Synology's proprietary VSMeta file. But; on to the problem.

I can't seem to run the application without error. After cloning the repo, I run the following command in the same folder as nfo.java and my test NFO file:

`java nfo.java test.nfo test.vsmeta`

The exact error produced is:
```
nfo.java:67: error: illegal start of expression
	public static void action(File nfo,File target) throws ParserConfigurationException, SAXException, IOException, NullPointerException {
	^
1 error
error: compilation failed
```

Here is the output of java --version from my machine:
```
java 13.0.2 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
```

Finally, here is the XML of my test.nfo file:
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<movie>
    <title>Star Wars (99 second cut)</title>
    <runtime>2</runtime>
    <set>Star Wars Saga</set>
    <sorttitle>Star Wars 01</sorttitle>
    <genre clear="true">SciFi</genre>
    <genre>Romance</genre>
    <genre>Action</genre>
</movie>
```

I'm running this on MacOS Big Sur version 11.1 on a MacBook Pro (16-inch, 2019). Let me know if you need any other details for troubleshooting or if you'd like me to test a new build; happy to help.

**Comment by dengyull** [comment]
I update the file, there's one bracket I lose.

**Comment by dengyull** [comment]
the converter base on search the mp4 file, if you like to use my version make sure your nfo file names with the .mp4.nfo. or you can modify it if you need.

**Comment by bhelmick** [comment]
You. Are. A. Genius.

The tool works and successfully converted the mp4 and nfo file into a valid VSMeta file the results you can see below in a screenshot from my Video Station. Well done! And thank you for fixing it so quickly.

My next steps from here are to start testing more metadata in the NFO specifically to include all of the meta that I have embedded in the MP4 files themselves. As I continue testing I'll let you know the results and file new bugs if I find other issues.

Question. Does the tool handle cover art? Will it, for example, look for "test.jpg" and embed it into the vsmeta file?

![Screen Shot 2020-12-29 at 9 28 49 PM](https://user-images.githubusercontent.com/3171691/103326313-cedc8e80-4a1d-11eb-9104-572b33b2e712.png)

**Comment by dengyull** [comment]
I can't find the binary value with the cover index, I did use a rename function to convert it, it is accessible and more simple. the background is in the same situation.  you just need to use a batch rename, then setup in the ds video, turn on the video cover setting.
