### ISSUE TITLE
封面图写不进去啊

### ISSUE THREAD

**Issue by 1525745393** [dengyull/Synology-vsmeta#3]

**Comment by dengyull** [comment]
是的，poster写入我没解析出来，考虑到可以设置poster.jpg，我也没继续研究了。

**Comment by 1525745393** [comment]
批量导入视频poster.jpg格式封面群晖检索不到

**Comment by 1525745393** [comment]
手动改有点头大

**Comment by dengyull** [comment]
在video station里设置，或者你也可以写个批处理设置
![image](https://github.com/dengyull/Synology-vsmeta/assets/43188363/9af67900-a7a8-4b2b-96e7-60bc1906f9ae)

**Comment by 1525745393** [comment]
我的文件格式是这样的
![IMG_20240302_020849.jpg](https://github.com/dengyull/Synology-vsmeta/assets/106818742/d26b77fe-1b9c-4fc9-8ecd-913155a3f225)

设置-poster.jpg群晖没反应

**Comment by dengyull** [comment]
video station不支持文件名-popst.jpg,你需要重命名成poster.jpg，你可以写个批处理解决，识别视频文件名并copy封面。

**Comment by 1525745393** [comment]
显示这样![Screenshot_2024-03-02-02-13-16-944_com.synology.dsvideo.jpg](https://github.com/dengyull/Synology-vsmeta/assets/106818742/4f6cdbac-ade9-493f-8cdf-7c42e9ec1908)

**Comment by dengyull** [comment]
或者你用everything批量重命名。

**Comment by dengyull** [comment]
![image](https://github.com/dengyull/Synology-vsmeta/assets/43188363/abf2adf3-5509-4853-9e59-f76ea005c888)
---> ![image](https://github.com/dengyull/Synology-vsmeta/assets/43188363/6111c318-3b03-4c81-88d6-c39c7de344f4)

**Comment by 1525745393** [comment]
你那批量处理的怎么写的

**Comment by dengyull** [comment]
请用everything的重命名，把群晖映射到Windows中，搜索-poster.jpg,f2重命名，把-poster前面的删除。

**Comment by 1525745393** [comment]
everything会使用，大佬改名后Emby还支持不

**Comment by dengyull** [comment]
支持的。

**Comment by 1525745393** [comment]
好的，谢谢，明天试一下

**Comment by 1525745393** [comment]
搞定了 提供下新思路 用按键精灵 自动直接在文件夹里选封面 背景图
